package uz.pdp.uzummarket.enums;

public enum OrderStatus {
    NEW,        /// BU ZAKAS URULGANI
    DELIVERED,  /// BU YETQIZIB BERILGAN PUNKITGAMI YOKI UYIGACHAMI
    COMPLETED,  /// YAKUNLANDI YANI USER QABUL QILDI ZAKASINI
    CANCELLED,  /// ADMIN TARAFDAN ATMEN
    REJECT      ///USER TARAFDAN ATMEN QILINGANI

}
